export const ROUTES = {
  accueil: "/",
  actifs: "/actifs",
  carte: "/carte",
  historique: "/historique",
  nouveau: "/nouveau",
  modifier: (id: string) => `/nouveau/${id}`,
  validation: "/validation",
  references: "/references",
  tableauBord: "/tableau-de-bord",
  notifications: "/notifications",
  journal: "/journal",
  admin: "/admin",
  login: "/login",
} as const;
